# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp

# Include any dependencies generated for this target.
include CMakeFiles/format_reader.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/format_reader.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/format_reader.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/format_reader.dir/flags.make

CMakeFiles/format_reader.dir/detectwebcam_IR.o: CMakeFiles/format_reader.dir/flags.make
CMakeFiles/format_reader.dir/detectwebcam_IR.o: detectwebcam_IR.cpp
CMakeFiles/format_reader.dir/detectwebcam_IR.o: CMakeFiles/format_reader.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/format_reader.dir/detectwebcam_IR.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/format_reader.dir/detectwebcam_IR.o -MF CMakeFiles/format_reader.dir/detectwebcam_IR.o.d -o CMakeFiles/format_reader.dir/detectwebcam_IR.o -c /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp/detectwebcam_IR.cpp

CMakeFiles/format_reader.dir/detectwebcam_IR.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/format_reader.dir/detectwebcam_IR.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp/detectwebcam_IR.cpp > CMakeFiles/format_reader.dir/detectwebcam_IR.i

CMakeFiles/format_reader.dir/detectwebcam_IR.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/format_reader.dir/detectwebcam_IR.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp/detectwebcam_IR.cpp -o CMakeFiles/format_reader.dir/detectwebcam_IR.s

# Object files for target format_reader
format_reader_OBJECTS = \
"CMakeFiles/format_reader.dir/detectwebcam_IR.o"

# External object files for target format_reader
format_reader_EXTERNAL_OBJECTS =

libformat_reader.so: CMakeFiles/format_reader.dir/detectwebcam_IR.o
libformat_reader.so: CMakeFiles/format_reader.dir/build.make
libformat_reader.so: /usr/local/lib/libopencv_imgcodecs.so.4.7.0
libformat_reader.so: /usr/local/lib/libopencv_imgproc.so.4.7.0
libformat_reader.so: /usr/local/lib/libopencv_core.so.4.7.0
libformat_reader.so: CMakeFiles/format_reader.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX shared library libformat_reader.so"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/format_reader.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/format_reader.dir/build: libformat_reader.so
.PHONY : CMakeFiles/format_reader.dir/build

CMakeFiles/format_reader.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/format_reader.dir/cmake_clean.cmake
.PHONY : CMakeFiles/format_reader.dir/clean

CMakeFiles/format_reader.dir/depend:
	cd /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp /home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp/CMakeFiles/format_reader.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/format_reader.dir/depend

