# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DIMPLEMENT_FORMAT_READER -DUSE_OPENCV -Dformat_reader_EXPORTS

CXX_INCLUDES = -I/home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp -I/home/ss21mipt/Documents/starkit/DIPLOMA/YOEO/yoeo/detectwebcam_IR_cpp/.. -isystem /usr/local/include/opencv4

CXX_FLAGS = -fPIC

