name: Ubuntu CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Pin setup tools (remove for next torch release)
      run: poetry run pip install setuptools==59.5.0

      # Prints the help pages of all scripts to see if the imports etc. work
    - name: Test the help pages
      run: |
        poetry run yoeo-train -h
        poetry run yoeo-test -h
        poetry run yoeo-detect -h

      # - name: Demo Training
      #   run: poetry run yoeo-train --data config/custom.data  --model config/yolov3.cfg --epochs 30

      # - name: Demo Evaluate
      #   run: poetry run yoeo-test --data config/custom.data  --model config/yolov3.cfg --weights checkpoints/yolov3_ckpt_29.pth

      # - name: Demo Detect
      #   run: poetry run yoeo-detect --batch_size 2 --weights checkpoints/yolov3_ckpt_29.pth


  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Flake8
        uses: TrueBrain/actions-flake8@master
        with:
          only_warn: 1
          max_line_length: 150
          path: yoeo
