name: CI

on: [pull_request, workflow_dispatch]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-24.04, ubuntu-22.04, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: "poetry"

      - name: Install Dependencies
        run: poetry install --with dev

      # Prints the help pages of all scripts to see if the imports etc. work
      - name: Test the help pages
        run: |
          poetry run yoeo-train -h
          poetry run yoeo-test -h
          poetry run yoeo-detect -h

      - name: Demo Training
        run: poetry run yoeo-train --data config/custom.data --epochs 30

      - name: Demo Evaluate
        run: poetry run yoeo-test --data config/custom.data --weights checkpoints/yoeo_checkpoint_29.pth

      - name: Demo Detect
        run: poetry run yoeo-detect --batch_size 2 --weights checkpoints/yoeo_checkpoint_29.pth

  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Flake8
        uses: TrueBrain/actions-flake8@master
        with:
          only_warn: 1
          max_line_length: 150
          path: yoeo
