name: Ubuntu CI

on: [push, pull_request, workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    outputs:
      output_python_version: ${{ steps.setup_python.outputs.python-version }}
      output_cache_hit: ${{ steps.setup_python.outputs.cache-hit }}
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      id: setup_python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"  # ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install

      # Prints the help pages of all scripts to see if the imports etc. work
    - name: Test the help pages
      run: |
        poetry run yoeo-train -h
        poetry run yoeo-test -h
        poetry run yoeo-detect -h

      # - name: Demo Training
      #   run: poetry run yoeo-train --data config/custom.data  --model config/yolov3.cfg --epochs 30

      # - name: Demo Evaluate
      #   run: poetry run yoeo-test --data config/custom.data  --model config/yolov3.cfg --weights checkpoints/yolov3_ckpt_29.pth

      # - name: Demo Detect
      #   run: poetry run yoeo-detect --batch_size 2 --weights checkpoints/yolov3_ckpt_29.pth

  echo-results:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - run: echo ${{needs.main.outputs.output_python_version}} ${{needs.main.outputs.output_cache_hit}}


  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Flake8
        uses: TrueBrain/actions-flake8@master
        with:
          only_warn: 1
          max_line_length: 150
          path: yoeo
